### ISSUE TITLE
Update the how to create GitBucket plugin tutorial

### ISSUE THREAD

**Issue by takezoe** [gitbucket/gitbucket-news#50]
This article is out of date. We need to update.
https://gitbucket.github.io/gitbucket-news/gitbucket/2015/06/29/how-to-create-plugin.html

Also, we should mention about the classpath isolation in GitBucket plugins in this article.

**Comment by aadrian** [comment]
@takezoe also it would make it easier to start if the gitbucket-plugin-template would be a SBT G8 template: https://github.com/gitbucket/gitbucket-plugin-template/issues/2

**Comment by takezoe** [comment]
Updated the article to use sbt-gitbucket-plugin.
